name: Build & Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build_and_test:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v
